---
title: blank
timezone: UTC
collections:
  news:
    title: News
    output: true
    permalink: "/news/:path/"
    defaults:
      layout: post
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: assets
  values:
    sitemap: false
first_name: 
middle_name: 
last_name: Işıl Candemir, Ph.D
email: isilcandemir@gmail.com
description: 'A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio)
  design.

'
footer_text: 'Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a>
  with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

'
keywords: jekyll, jekyll-theme, academic-website, portfolio-website
lang: en
icon: "⚛️"
url: isilcandemir2.github.io
baseurl: 
last_updated: false
impressum_path: 
highlight_theme_light: github
highlight_theme_dark: native
repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed
navbar_fixed: true
footer_fixed: true
max_width: 800px
serve_og_meta: false
serve_schema_org: false
og_image: 
github_username: 
gitlab_username: 
twitter_username: 
mastodon_username: 
orcid_id: 0000-0003-1526-7042
linkedin_username: isilcandemir
telegram_username: 
scholar_userid: 
semanticscholar_id: 
whatsapp_number: 
medium_username: 
quora_username: 
publons_id: 
lattes_id: 
osf_id: 
research_gate_profile: 
scopus_id: 
blogger_url: 
work_url: 
keybase_username: 
wikidata_id: 
wikipedia_id: 
dblp_url: 
stackoverflow_id: 
kaggle_id: 
lastfm_id: 
spotify_id: 
pinterest_id: 
unsplash_id: 
instagram_id: 
facebook_id: 
youtube_id: 
discord_id: 
contact_note: 'Please feel free to contact me via email.

'
announcements:
  enabled: true
  scrollable: true
  limit: 5
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
include:
- _pages
exclude:
- bin
- Gemfile
- Gemfile.lock
- vendor
keep_files:
- CNAME
- ".nojekyll"
- ".git"
plugins:
- jekyll-archives
- jekyll-diagrams
- jekyll-email-protect
- jekyll-feed
- jekyll-imagemagick
- jekyll-link-attributes
- jekyll-minifier
- jekyll-paginate-v2
- jekyll/scholar
- jekyll-sitemap
- jekyll-toc
- jekyll-twitter-plugin
- jemoji
jekyll-minifier:
  exclude:
  - robots.txt
  uglifier_args:
    harmony: true
jekyll-archives:
  enabled:
  - year
  - tags
  - categories
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: "/blog/:year/"
    tag: "/blog/tag/:name/"
    category: "/blog/category/:name/"
display_tags:
- formatting
- images
- links
- math
- code
scholar:
  last_name:
  - Einstein
  first_name:
  - Albert
  - A.
  style: apa
  locale: en
  source: "/_bibliography/"
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters:
  - latex
  - smallcaps
  - superscript
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"
filtered_bibtex_keywords:
- abbr
- abstract
- arxiv
- bibtex_show
- html
- pdf
- selected
- supp
- blog
- code
- poster
- slides
- website
- preview
- altmetric
max_author_limit: 3
more_authors_animation_delay: 10
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude: 
imagemagick:
  enabled: true
  widths:
  - 480
  - 800
  - 1400
  input_directories:
  - assets/img/
  input_formats:
  - ".jpg"
  - ".jpeg"
  - ".png"
  - ".tiff"
  output_formats:
    webp: "-resize 800x"
jekyll-diagrams: 
enable_google_analytics: false
enable_panelbear_analytics: false
enable_google_verification: false
enable_bing_verification: false
enable_masonry: true
enable_math: true
enable_tooltips: false
enable_darkmode: false
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true
academicons:
  version: 1.9.1
  integrity: sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg=
bootstrap:
  version: 4.6.1
  integrity:
    css: sha256-DF7Zhf293AJxJNTmh5zhoYYIMs2oXitRfBjY+9L//AY=
    js: sha256-fgLAgv7fyCGopR/gBNq2iW3ZKIdqIcyshnUULC4vex8=
bootstrap-table:
  version: 1.21.4
fontawesome:
  version: 5.15.4
  integrity: sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4=
jquery:
  version: 3.6.0
  integrity: sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=
mathjax:
  version: 3.2.0
masonry:
  version: 4.2.2
  integrity: sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI=
mdb:
  version: 4.20.0
  integrity:
    css: sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw=
    js: sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA=
medium_zoom:
  version: 1.0.8
  integrity: sha256-7PhEpEWEW0XXQ0k6kQrPKwuoIomz8R8IYyuU1Qew4P8=
